# Generated by Django 4.2.4 on 2023-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_client', models.CharField(max_length=70, verbose_name='email')),
                ('Name', models.CharField(max_length=20, verbose_name='phone_number')),
            ],
        ),
    ]
