# Generated by Django 4.2.4 on 2023-10-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
