# Generated by Django 4.2.4 on 2023-09-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='name_category')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_product', models.ImageField(upload_to='product/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description_product', models.TextField(verbose_name='Descripción')),
                ('price_product', models.IntegerField(verbose_name='Precio')),
                ('quantity_product', models.IntegerField(verbose_name='Cantidad')),
                ('code_product', models.CharField(max_length=20, verbose_name='Código')),
                ('categories_product', models.ManyToManyField(to='product.category')),
                ('distributed_by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('image_product', models.ManyToManyField(to='product.imagesproduct')),
            ],
        ),
    ]
