# Generated by Django 4.2.4 on 2023-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='name_category')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_product', models.ImageField(upload_to='product/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=40, verbose_name='name_product')),
                ('description_product', models.TextField(verbose_name='description_product')),
                ('price_product', models.IntegerField(verbose_name='price_product')),
                ('quantity_product', models.IntegerField(verbose_name='quantity_product')),
                ('code_product', models.CharField(max_length=20, verbose_name='code_product')),
                ('categories_product', models.ManyToManyField(to='product.category')),
                ('distributed_by_product', models.ManyToManyField(to='seller.seller')),
                ('image_product', models.ManyToManyField(to='product.imagesproduct')),
            ],
        ),
    ]
