# Generated by Django 4.2.4 on 2023-08-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='distributed_by_product',
        ),
        migrations.AddField(
            model_name='product',
            name='distributed_by_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
            preserve_default=False,
        ),
    ]
