# Generated by Django 4.2.4 on 2023-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_distributed_by_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_product',
            field=models.TextField(verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=40, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_product',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
