# Generated by Django 4.2.4 on 2023-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('calidad', models.IntegerField()),
            ],
        ),
    ]
